CREATE DATABASE MARINGAATIVA;

USE MARINGAATIVA;

CREATE TABLE CENTRO(
	IDCENTRO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) DEFAULT NULL,
	DESCRICAO VARCHAR (200),
	AVISO VARCHAR (100)
);

CREATE TABLE ENDERECO_CENTRO (
	IDENDERECO_CENTRO INT PRIMARY KEY AUTO_INCREMENT,
	CEP_CETRO VARCHAR(8) NOT NULL,
	RUA_CENTRO VARCHAR(30) NOT NULL,
	BAIRRO_CENTRO VARCHAR(30) NOT NULL,
	ESTADO_CENTRO CHAR(2) NOT NULL,
	CIDADE_CENTRO VARCHAR (30) NOT NULL,
	NENDE_CENTRO INT (5) NOT NULL,
	COMPLEMENTO_CENTRO VARCHAR (10),
	ID_CENTRO INT UNIQUE,
	FOREIGN KEY (ID_CENTRO) REFERENCES CENTRO(IDCENTRO)
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME_CLIENTE VARCHAR(30) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(10) NOT NULL,
	TELEFONE VARCHAR(10) NOT NULL,
	DATA_NASC VARCHAR (10) NOT NULL,
	SEXO ENUM('M','F') NOT NULL
);

CREATE TABLE ENDERECO_CLIENTE(
	IDENDERECO_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	CEP_CLIENTE VARCHAR(8) NOT NULL,
	RUA_CLIENTE VARCHAR(30) NOT NULL,
	BAIRRO_CLIENTE VARCHAR(30) NOT NULL,
	ESTADO_CLIENTE CHAR(2) NOT NULL,
	CIDADE_CLIENTE VARCHAR (20) NOT NULL,
	NENDE_CLIENTE INT (5) NOT NULL,
	COMPLEMENTO_CLIENTE VARCHAR (10),
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE AGENDA (
	IDAGENDA INT PRIMARY KEY AUTO_INCREMENT,
	DISPONIBILIDADE ENUM('DISPONIVEL', 'INDISPONIVEL') NOT NULL,
	TEMPO_ALOCACAO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_CENTRO INT NOT NULL,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE),
	FOREIGN KEY (ID_CENTRO)
	REFERENCES CENTRO(IDCENTRO)
);